version: 2

models:
  - name: fct_stock_performance
    description: "Финальная витрина данных с показателями акций и скользящими средними"
    columns:
      - name: trading_date
        tests:
          - not_null

      - name: ticker
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['AAPL', 'MSFT', 'NVDA', 'TSLA', 'AMZN', 'BABA', 'NFLX', 'META', 'AMD', 'GOOGL']

      - name: close_price
        tests:
          - not_null

      - name: moving_avg_3d
        tests:
          - not_null